package com.bravura.finco.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;

import java.io.Serializable;

@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Builder
@JsonIgnoreProperties(ignoreUnknown = true)
@Schema(name = "NLPResponse", description = "NLP Response Details")

public class NLPResponse implements Serializable {
    @Schema(
            format = "string",
            description = "key to uniquely identify a response.",
            accessMode = Schema.AccessMode.READ_ONLY,
            example = "afv2ewr4")
    @JsonProperty("nlpResponseId")
    private String nlpResponseId;

    @Schema(
            format = "string",
            description = "Name of the product",
            accessMode = Schema.AccessMode.READ_ONLY,
            example = "10001")
    @JsonProperty("PROD")
    private String PROD;

    @Schema(
            format = "string",
            description = "Service name for the product",
            accessMode = Schema.AccessMode.READ_ONLY,
            example = "Distribution Details")
    @JsonProperty("SER")
    private String SER;

    @Schema(
            format = "string",
            description = "Identifier for a service",
            accessMode = Schema.AccessMode.READ_ONLY,
            example = "Distribution Details")
    @JsonProperty("ID")
    private String ID;

    @Schema(
            format = "string",
            description = "HTML span generated by NLP",
            accessMode = Schema.AccessMode.READ_ONLY,
            example = "<span>Hi</span>")
    @JsonProperty("span")
    private String span;

    @Schema(
            format = "string",
            description = "Identifier for a intent",
            accessMode = Schema.AccessMode.READ_ONLY,
            example = "Distribution Details")
    @JsonProperty("intent")
    private String intent;

    @Schema(
            format = "integer",
            description = "Identifier for a intent confidence",
            accessMode = Schema.AccessMode.READ_ONLY,
            example = "68")
    @JsonProperty("confidence")
    private Integer intentConfidence;


}
